/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dat076.blogbox.bb;

import com.dat076.blogbox.core.User;
import com.dat076.blogbox.core.UserRegistry;
import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;
import javax.inject.Named;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;

/**
 *
 * @author hajo
 */
@Named("addUser")
@RequestScoped  // NOTE enterprise package, else disaster!!!
public class AddUserBB {
    
    @Size(min = 4, max = 20, message= "Not implemented yet")
    @NotNull(message="Not implemented yet")
    private String name;
    @Pattern(regexp = "*[@]*.*",message="Not implemented yet")
    @NotNull(message="Not implemented yet")
    private String email;
    @Inject
    private UserRegistry ur;

    public String save() {
        // Id generated by database
        User u = new User(name,email);
        ur.add(u);
        return "newUser";  // TODO
    }
    
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getEmail() {
        return email;
    }

 
}
